[package]
name = "expr-git-cliff"
version = "0.3.1"
authors = ["Wink Saville <wink@saville.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
